name: Azure App Service CI/CD

on:
  push:
    branches:
      - main  # Set the branch name to trigger deployment (e.g., main, master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x'  # Update with your desired .NET version

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test with dotnet
      run: dotnet test

    - name: Publish to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Resume-Ranking-Tool'  # Replace with your Azure App Service name
        
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}  # Store your publish profile as a GitHub secret
